#!/usr/bin/env bash
# verify-po: independent verification of an A-GKR bench-result.
#   TREE=art:<run-files> TAG=<name> TARGET=<profile> MODEL=<tc model> [NEGTREE=art:<producer negatives tree>] bash 08-agkr-verify.sh
# Verifier: verity-gkr-verify (backends/gkr/verifier, no dependencies) from MY tree /workspace/src (main ab9573fd), built and
#   tested here (target dir /workspace/agkr-target).
# Statement: circuit files regenerated by the producer's named source /workspace/agkr-07a8edd6 (git archive of lane/agkr-fp8
#   @ 07a8edd6; main lacks the E4M3 builder) and compared byte for byte; public.bin vs the frozen TARGET y drawn by MY tree
#   (07-agkr-fp8-statement.py).
# Negatives: `mutate --sample 64` on rep0 (every mutation rejected); the producer's named negatives (NEGTREE) with MY binary;
#   my own public.bin word +1 on VU 17 (must be rejected).
set -uo pipefail
source /workspace/env.sh
set -a; . /root/r2.env; set +a
export PATH=$HOME/.cargo/bin:$PATH CARGO_TARGET_DIR=/workspace/agkr-target
V=$CARGO_TARGET_DIR/release/verity-gkr-verify
O=/workspace/verify-po/agkr-$TAG; mkdir -p $O
PSRC=/workspace/agkr-07a8edd6/src
{
if [ ! -x $V ]; then
  echo "=== [$(date -u +%H:%M:%S)] build + test verity-gkr-verify from /workspace/src"
  (cd /workspace/src/backends/gkr/verifier && cargo build --release 2>&1 | tail -2 && cargo test --release 2>&1 | grep -E '^test result|FAILED|panicked')
fi
sha256sum $V
echo "=== [$(date -u +%H:%M:%S)] fetch $TREE"
[ -d $O/tree ] || $PY -m research data fetch $TREE --to $O/tree | tail -1
D=$(dirname $(find $O/tree -name public.bin | head -1))/..; D=$(cd $D && pwd); echo "tree: $D"
sha256sum $D/proofs/*.bin $D/statement/*
echo "=== [$(date -u +%H:%M:%S)] regenerate the statement files with the producer's named source ($(cat /workspace/agkr-07a8edd6/REV))"
(cd $PSRC/backends/gkr && PYTHONPATH=$PSRC/backends/gkr:$PSRC/packages/verity/src:$PSRC/backends/numerical/python:$PSRC \
   $PY -m gpu.v2.export circuits --model $MODEL --out $O/regen > $O/regen.json 2>&1; echo "regen rc=$?")
echo "=== [$(date -u +%H:%M:%S)] statement check (public.bin vs MY tree's frozen $TARGET)"
(cd /workspace/src && $PY $RESEARCH_RUN_DIR/inputs/07-agkr-fp8-statement.py $D/statement $O/regen "$TARGET" "$MODEL" > $O/statement-check.json 2>$O/statement-check.err; echo "check rc=$?")
grep -E '"(identical|ok|equals_frozen_y_packed|mismatched|manifest_params_differ|frozen_relation|y_rel_equals_pack)"' $O/statement-check.json
echo "=== [$(date -u +%H:%M:%S)] verify"
for r in $D/proofs/rep*.bin; do
  b=$(basename $r .bin)
  $V verify --dir $D/statement --proof $r --vus 4096 --threads 15 --json $O/out_$b.json > $O/verify_$b.log 2>&1; rc=$?
  echo "$b rc=$rc $(head -c 400 $O/out_$b.json 2>/dev/null)"
done
echo "=== [$(date -u +%H:%M:%S)] negative: my public.bin word +1 at VU 17"
rm -rf $O/neg-mine; cp -r $D/statement $O/neg-mine
$PY - $O/neg-mine/public.bin <<'EOF'
import struct, sys
p = sys.argv[1]; b = bytearray(open(p, "rb").read()); off = 16 + 4 * 17
w = struct.unpack_from("<I", b, off)[0]; struct.pack_into("<I", b, off, w + 1); open(p, "wb").write(b); print("VU 17:", w, "->", w + 1)
EOF
$V verify --dir $O/neg-mine --proof $D/proofs/rep0.bin --vus 4096 --threads 15 --json $O/neg-mine.json > $O/neg-mine.log 2>&1; echo "neg-mine rc=$? (non-zero expected) $(tail -c 300 $O/neg-mine.log)"
if [ -n "${NEGTREE:-}" ]; then
  echo "=== [$(date -u +%H:%M:%S)] producer's named negatives $NEGTREE with MY binary"
  [ -d $O/negtree ] || $PY -m research data fetch $NEGTREE --to $O/negtree | tail -1
  for nd in $(find $O/negtree -name proof.bin -printf '%h\n' | sort); do
    $V verify --dir $nd --proof $nd/proof.bin --vus 4096 --threads 15 > $O/negp-$(basename $nd).log 2>&1; rc=$?
    echo "$(basename $nd) rc=$rc $(tail -c 200 $O/negp-$(basename $nd).log | tr '\n' ' ')"
  done
fi
echo "=== [$(date -u +%H:%M:%S)] negatives (mutate --sample 64 on rep0)"
$V mutate --dir $D/statement --proof $D/proofs/rep0.bin --vus 4096 --threads 15 --sample 64 > $O/mutate.log 2>&1; echo "mutate rc=$?"
tail -3 $O/mutate.log
echo "=== [$(date -u +%H:%M:%S)] done"
} 2>&1 | tee -a $O/verify.out
