#!/usr/bin/env bash
# verify-po: A-GKR FP8 result on a merged-LK statement (lane/agkr-fp8 d5d80e0b merge_tables; handoff 20260925T0045Z).
#   TREE= TAG= TARGET= MODEL= PREV=<producer commit> NEGTREE= OLDSTMT=<dir of the unmerged statement verified earlier> bash 24-agkr-fp8-merged.sh
# 1. 08-agkr-verify.sh (main's verifier; statement regenerated by PREV's export and compared; public.bin vs main's frozen set;
#    negatives: mine, the producer's NEGTREE, mutate --sample 64).
# 2. PREV's export with --no-merge must reproduce OLDSTMT's circuit.txt byte for byte (the unmerged E4M3 circuit I verified
#    in request 3), and 23-lk-merge-check.py (MY tree's parser) must find the dumped merged circuit.txt to be exactly the
#    tag-merge of that unmerged circuit.
set -uo pipefail
source /workspace/env.sh
bash $RESEARCH_RUN_DIR/inputs/08-agkr-verify.sh
O=/workspace/verify-po/agkr-$TAG; PSRC=/workspace/agkr-$PREV/src
D=$(dirname $(find $O/tree -name public.bin | head -1)); echo "dumped statement: $D"
{
echo "=== [$(date -u +%H:%M:%S)] unmerged regen (--no-merge) with $PREV vs the earlier verified statement $OLDSTMT"
(cd $PSRC/backends/gkr && PYTHONPATH=$PSRC/backends/gkr:$PSRC/packages/verity/src:$PSRC/backends/numerical/python:$PSRC \
   $PY -m gpu.v2.export circuits --model $MODEL --no-merge --out $O/regen-nomerge > $O/regen-nomerge.json 2>&1; echo "regen --no-merge rc=$?")
for f in circuit.txt epilogue.txt chain.txt; do cmp $O/regen-nomerge/$f $OLDSTMT/$f && echo "$f: --no-merge == earlier verified statement"; done
echo "=== [$(date -u +%H:%M:%S)] LK merge check (my parser): unmerged $O/regen-nomerge vs dumped $D"
(cd /workspace/src/backends/gkr && PYTHONPATH=/workspace/src/backends/gkr:/workspace/src \
   $PY $RESEARCH_RUN_DIR/inputs/23-lk-merge-check.py $O/regen-nomerge/circuit.txt $D/circuit.txt > $O/lk-merge-check.json 2>$O/lk-merge-check.err; echo "lk-merge-check rc=$?")
grep -E '"(head_identical|one_table|query_problem_count|rows_equal_multiset|merged_first_col_unique|below_P|ok)"' $O/lk-merge-check.json
grep -A3 '"rows"' $O/lk-merge-check.json | head -4; grep -A12 '"tag_map"' $O/lk-merge-check.json | head -13; tail -3 $O/lk-merge-check.err
echo "=== [$(date -u +%H:%M:%S)] done (merged)"
} 2>&1 | tee -a $O/verify.out
