# machine vy-coord-check2: written by `research pods register`; one file per machine (research.pods.registry)
provider = "runpod"
pod_id = "c72e5j34okgj6g"
project = "verity"
guard = true
registered_by = "f76f5394c78b"
registered_at = "2026-09-28T09:26Z"
