# machine vy-flock-bench-cpu: written by `research pods register`; one file per machine (research.pods.registry)
provider = "runpod"
pod_id = "i856k93id9bf7g"
project = "verity"
guard = 45
registered_by = "Daniels-MacBook-Pro.local"
registered_at = "2026-09-25T07:54Z"
