[package]
name = "vu-k1536-guest"
version = "0.1.0"
edition = "2021"

[features]
guest = []

[dependencies]
jolt = { package = "jolt-sdk", path = "../../../jolt-sdk", features = [] }
jolt-inlines-sha2.workspace = true
serde = { version = "1", default-features = false, features = ["alloc"] }
serde_bytes = { version = "0.11", default-features = false, features = ["alloc"] }

[lib]
test = false
doctest = false
bench = false

[[bin]]
name = "vu-k1536-guest"
path = "src/main.rs"
test = false
bench = false
