#!/bin/sh
# ssh to vy-sp1-a100 (mj8cb81ecauzbi); `research pods ssh vy-sp1-a100 --print` gave this line.
exec ssh -n -i /Users/danielreuter/.runpod/ssh/runpodctl-ssh-key -p 16521 -o StrictHostKeyChecking=no -o UserKnownHostsFile=/Users/danielreuter/.runpod/ssh/veritor-campaign-known_hosts -o ServerAliveInterval=30 -o LogLevel=ERROR root@154.54.102.29 "$@"
