"""verify-bligero-real-k: the live verifier's own session records vs the cell and its dumped proofs.

  python sessions_check.py SESSIONS_DIR CELLS_JSON RUN_OUT_DIR PINS_DIR > out.json

SESSIONS_DIR: <verifier sessions dir snapshots> holding <session id>/{hello,verdict,session}.json and sub_XX.coins (read-only
copies taken over ssh from the producer's verifier pods).  CELLS_JSON: `research data select --kind bench-result/v1 --json`.
RUN_OUT_DIR: my pod run's cells/<art8>/files.json (sha256 of every dumped file, hashed on my pod after reverify's custody check).
PINS_DIR: my own compiles <relation>+<leaf>/system.bin (pins_check.py).
"""
import hashlib, json, sys
from pathlib import Path

sroots = [Path(p) for p in sys.argv[1].split(",")]
cells = {x["id"]: x for x in json.loads(Path(sys.argv[2]).read_text()) if "cell" in x["manifest"]["meta"]}
run_out, pins = Path(sys.argv[3]), Path(sys.argv[4])
want = sys.argv[5].split(",") if len(sys.argv) > 5 else list(cells)


def sdir(sid):
    return next(r / sid for r in sroots if (r / sid / "verdict.json").is_file())


out = {}
for cid in want:
    cid = next(c for c in cells if c.startswith(cid) or c[4:].startswith(cid))
    m = cells[cid]["manifest"]["meta"]
    rel = m["cell"]["relation"]
    fp = m["workload_fingerprint"]
    per_rep = m["validation"]["evidence"]["live_verifier"]["per_rep"]
    my_sys = hashlib.sha256((pins / rel / "system.bin").read_bytes()).hexdigest()
    files = json.loads((run_out / cid[4:12] / "files.json").read_text())
    problems, sessions = [], []
    coins_seen = {}
    for pr in per_rep:
        sid = pr["session_id"]
        d = sdir(sid)
        hello, verdict = json.loads((d / "hello.json").read_text()), json.loads((d / "verdict.json").read_text())
        subs = json.loads((d / "session.json").read_text())["subbatches"]
        b = verdict["batch"]
        chk = {
            "hello_run_id": hello["run_id"] == m["run_id"],
            "hello_relation": hello["relation"] == rel.split("+")[0],
            "hello_rep": hello["rep"] == pr["rep"],
            "hello_total_vus": hello["total_vus"] == fp["B"],
            "hello_n_proofs": hello["n_proofs"] == fp["N_subbatches"],
            "hello_zk_interactive": hello["zk"] is True and hello["mode"] == "interactive" and hello["target_bits"] >= 128,
            "system_sha256_eq_my_compile": hello["system_sha256"] == my_sys,
            "verdict_accepted": verdict["accepted"] is True and verdict["reason"] == "accepted",
            "all_received_accepted": verdict["proofs_received"] == verdict["n_proofs"] == verdict["accepted_subbatches"] == fp["N_subbatches"],
            "no_live_rejections_or_errors": not verdict["live_rejections"] and not verdict["errors"],
            "coins_from_verifier": verdict["coins"].startswith("generated by this verifier"),
            "batch_accept_128": b["batch_accepted"] is True and b["rejected"] == 0 and b["accepted"] == b["n"] == fp["N_subbatches"]
                                and b["own_coins"] == b["n"] and b["batch_bits"] >= 128,
            "batch_pinned_relation": b["system_pinned"] is True and b["system"]["pinned_relation"] == rel,
            "subbatch_records": len(subs) == fp["N_subbatches"] and all(s.get("live_check", {}).get("accepted") for s in subs),
        }
        coins = {f"sub_{s['sub']:02d}": hashlib.sha256((d / f"sub_{s['sub']:02d}.coins").read_bytes()).hexdigest() for s in subs}
        for k, h in coins.items():
            coins_seen.setdefault(h, []).append(f"{sid}/{k}")
        if pr["rep"] == 1:
            chk["rep1_proofs_eq_dump"] = all(files.get(f"rep1/sub_{s['sub']:02d}.proof") == s["proof_sha256"] for s in subs)
            chk["rep1_stmts_eq_dump"] = all(files.get(f"rep1/sub_{s['sub']:02d}.stmt") == s["stmt_sha256"] for s in subs)
            chk["rep1_coins_eq_dump"] = all(files.get(f"rep1/{k}.coins") == h for k, h in coins.items())
            chk["dump_system_eq_session"] = files.get("system.bin") == hello["system_sha256"]
            chk["dump_rep1_count"] = sum(1 for k in files if k.startswith("rep1/") and k.endswith(".proof")) == len(subs)
        bad = [k for k, v in chk.items() if not v]
        problems += [f"{sid}: {k}" for k in bad]
        sessions.append({"session": sid, "rep": pr["rep"], "verifier_host": verdict["verifier_host"], "verifier_dc": verdict["verifier_dc"],
                         "ligero_verify_sha256": verdict["ligero_verify_sha256"], "bytes_in": verdict["bytes_in"],
                         "batch_bits": b["batch_bits"], "checks_failed": bad})
    reused = {h: v for h, v in coins_seen.items() if len(v) > 1}
    if reused:
        problems.append(f"coins reused across sub-batches/sessions: {list(reused.values())[:3]}")
    out[cid] = {"relation": rel, "run": m["run_id"], "sessions": sessions, "coins_distinct": not reused,
                "n_sessions": len(sessions), "ok": not problems, "problems": problems}
print(json.dumps(out, indent=1))
sys.exit(0 if all(v["ok"] for v in out.values()) else 1)
