"""SP1 core per-shard soundness (soundcalc, UDR, round-by-round) under stock and raised parameters.

Run: cd <soundcalc checkout @2af5e7d> && uv run --with toml python <this file>
The core circuit section is soundcalc's own zkvms/sp1/sp1.toml (generated by SP1's gen_soundcalc_toml; the constants
it reads are identical in v6.4.0 f66b4bff5).  Only the listed keys are overridden per variant.
"""
import copy
import math
from pathlib import Path

import toml

from soundcalc.zkvms.zkvm import zkVM

BASE = toml.load(Path("soundcalc/zkvms/sp1/sp1.toml"))
LOG2_DEFICIT = math.log2(1.0 / (0.5 + 0.25 / 2))  # -log2(5/8), SP1's unique_decoding_queries denominator


def sp1_queries(target_bits: int, pow_bits: int = 16) -> int:
    return math.ceil((target_bits - pow_bits) / LOG2_DEFICIT)


def core_levels(**over) -> dict:
    cfg = copy.deepcopy(BASE)
    cfg["circuits"] = [c for c in cfg["circuits"] if c["name"] == "core"]
    core = cfg["circuits"][0]
    lookup_over = {k[len("lookup."):]: v for k, v in over.items() if k.startswith("lookup.")}
    for k, v in over.items():
        if not k.startswith("lookup."):
            core[k] = v
    for k, v in lookup_over.items():
        core["lookups"][0][k] = v
    p = Path("/tmp/sp1-128-core.toml")
    p.write_text(toml.dumps(cfg))
    (c,) = zkVM.load_from_toml(p).get_circuits()
    (lv,) = c.get_security_levels().values()
    return lv


def show(name: str, lv: dict) -> None:
    commits = {k: v for k, v in lv.items() if k.startswith("commit round")}
    worst_commit = min(commits.items(), key=lambda kv: kv[1])
    below = sorted((k for k, v in lv.items() if k != "total" and v < 128), key=lambda k: lv[k])
    print(f"{name}: total {lv['total']} | query {lv['query phase']} lookup {lv['lookup']} batching {lv['batching']} "
          f"zerocheck {lv['zerocheck']} reduce {lv['reduce to dense PCS']} worst-commit {worst_commit} | "
          f"{len(below)} rounds < 128: {', '.join(f'{k}={lv[k]}' for k in below[:8])}{' ...' if len(below) > 8 else ''}")


if __name__ == "__main__":
    for t in (100, 128, 133, 134):
        print(f"SP1_TARGET_BITS_OF_SECURITY={t}: unique_decoding_queries = {sp1_queries(t)}")
    show("stock (124 q)", core_levels())
    for t in (128, 133, 134):
        show(f"target {t} ({sp1_queries(t)} q)", core_levels(num_queries=sp1_queries(t)))
    # every grinding knob SP1 has as a constant, raised as far as the formulas need
    show("134 + GKR_GRINDING 40 + BATCH_GRINDING 29",
         core_levels(num_queries=sp1_queries(134), grinding_batching_phase=29, **{"lookup.grinding_bits_lookup": 40}))
    # plus per-round commit-phase grinding (SP1 has no such knob: a protocol change)
    show("... + commit-phase grinding 25 (not in SP1)",
         core_levels(num_queries=sp1_queries(134), grinding_batching_phase=29, grinding_commit_phase=25,
                     **{"lookup.grinding_bits_lookup": 40}))
