"""Writes Pouw/PearlC/HotGamma.lean: v2-hot's price twins, generic over the H_i sizing rule, and their values.

python3 gen_hot_gamma.py   (from this folder; exact arithmetic, stdlib only)
"""
from fractions import Fraction as F
from pathlib import Path

R, RHO = 32, F(1, 1000)
SIZES = (8192, 16384)
# the statement's cast, GPU 0's 64-bit-store cast (server.md 10:25Z), and the kernel's as-written and packed casts
CASTS = {"Cast8": F(8), "Cast8p72": F(872, 100), "Cast32p06": F(3206, 100), "Cast16": F(16)}
ALL_RULES = {"Cast8", "Cast8p72"}  # casts with values for every sizing rule; the others have values at C0 only
# name, Lean prices, (add, bf16, fs, qa), c as a Lean term given the cast h
RECORDS = {
    "": ("Prices.sm120", (F(8), F(2), F(40), F(1)), lambda h: (h - 8, f"{lean(h)} - 8")),
    "Loop": ("Prices.sm120Loop", (F(1047, 125), F(2), F(40), F(2)),
             lambda h: (h - F(8953, 1000), f"{lean(h)} - 8953 / 1000")),
}
RULES = {"publicConst": lambda p, n: F(0), "colRms": lambda p, n: F(423, 50) * n * n}  # colRms: the FMA at 8.46
LEAN_RULE = {"publicConst": "(HotSizing.publicConst c₀)", "colRms": "HotSizing.colRms"}
C0 = 64  # the fixed rule, HotSizing.publicConst 64 (bc-b58c6093, ttout-restatements.md §8, 13:05Z)


def lean(q):
    return str(q.numerator) if q.denominator == 1 else f"{q.numerator} / {q.denominator}"


def gamma(p, rule, c, n, co=False):
    n = F(n)
    mk = n * n
    credit = n ** 3 + mk * R + 2 * p[1] * R * mk + p[2] * mk + p[0] * mk
    wref = credit + (p[3] + c) * mk + RULES[rule](p, n)
    den = credit - p[2] * mk - RHO * credit if co else (1 - RHO) * credit
    return 1 - F(399, 400) / (wref / den)


def pct(q):
    return f"{float(q) * 100:.5f}%"


HEADER = '''import Pouw.PearlC.TileGamma
import Pouw.PearlC.DeviceHot

/-!
# v2-hot's price twins, generic over the H_i sizing rule (the price-twins lane's file; staged)

Generated by `v2-hot/gen_hot_gamma.py` in `internal/pouw/price-twins-lean/`.

* **γ from TT_OUT at any v2-hot protocol** (`pearlCGammaHotAt`, `pearlCSampledHotAt`): if the protocol meets v2-hot's
  accounting at a record (`HotUnitAccounting`, `HotTileAccounting`), TT_OUT at it gives `G_γ` (per tile, `GγSampled`) at
  `gammaHot d h c ρ s`.
* **The twins** (`pearlC{Gamma,Sampled}Sm120v2Hot{,Loop}{Cast8,Cast8p72,Cast32p06,Cast16}_{8192,16384}`): v2 at the
  cap 1/1,000, at a record with `G = 0` and the issue-bound (`Prices.sm120`) or in-loop (`Prices.sm120Loop`) prices,
  against `W_ref` with the honest cast at the statement's 8, at 8.72, or at the kernel's as-written 32.06 and packed
  16, for **every** sizing rule `h`. Choosing between
  `HotSizing.publicConst` and `HotSizing.colRms` instantiates `h`; nothing is re-proved. `c` is the honest cast less the
  credited 8, plus, in the loop, the measured A-only forming 1.047 less the record's 2, so `W_ref` is exact at both
  prices.
* **The values** (`gammaHot_…`): `gammaHot` at each twin's record, cast and shape, by `norm_num`. At the casts 8 and
  8.72 they are given for both sizing rules, the public-constant ones for any `c₀`. The `…_publicConst64_…` ones, at
  every cast, are at the fixed rule `HotSizing.publicConst 64` (`ttout-restatements.md` §8), which the published
  figures cite.
* **The chain-only reading**, the same way (`pearlCGammaHotChainOnlyAt`, `pearlCSampledHotChainOnlyAt`, the
  `…ChainOnly_…` twins and the `gammaHotChainOnly_…` values): the credit less the forming, with the cap on the full
  credit. A
  chain-only protocol has the forming-credited one's game (neither `G_γ` nor `GγSampled` reads the credit), and its
  TT_OUT is weaker (`../ChainOnlyGamma.lean`'s argument).
-/

namespace Pouw.PearlC

open Pouw.PearlC.Assumptions

/-- TT_OUT at a protocol meeting v2-hot's per-unit accounting gives `G_γ` at `gammaHot d h c ρ s`. -/
theorem pearlCGammaHotAt {Q R S : Type} [Fintype Q] [DecidableEq Q] [Fintype R] [Fintype S] (CM : CostModel Q R S)
    (P : Protocol Q R S) (D : Layout → Prop) (d : PearlCDevice) (h : HotSizing) (c ρ : ℚ) (s : Shape) (hρ : ρ < 1)
    (hC : 0 < creditDevHot d s) (hW0 : 0 < wrefDevHot d h c s) (hacc : HotUnitAccounting P D d h c ρ s)
    (hTT : TTOut CM P D (1 / 400) εPearlC) :
    Gγ CM P D (gammaHot d h c ρ s : ℝ) εPearlC := by
  have hden : 0 < (1 - ρ) * creditDevHot d s := mul_pos (by linarith) hC
  set ω := wrefDevHot d h c s / ((1 - ρ) * creditDevHot d s) with hωdef
  have hω0 : 0 < ω := div_pos hW0 hden
  have hid : wrefDevHot d h c s = ω * ((1 - ρ) * creditDevHot d s) := by
    rw [hωdef, div_mul_cancel₀ _ hden.ne']
  have hW : ∀ U : Workload, U.InDomain P D → ∀ (H : Q → R) (s' : S), ∀ u < U.layout.N, ∀ act : Codes,
      P.actOK (U.layout.shape u) act → P.capOK H s' U u act → P.Wref U.layout u ≤ (ω : ℝ) * P.credit H s' U u act := by
    intro U hU H s' u hu act ha hcap
    obtain ⟨hw, hcr⟩ := hacc U hU H s' u hu act ha hcap
    rw [hw, hid]
    push_cast
    exact mul_le_mul_of_nonneg_left (by exact_mod_cast hcr) (by exact_mod_cast hω0.le)
  have key := gammaFromTTOut CM P D (1 / 400) (ω : ℝ) εPearlC (by exact_mod_cast hω0) hW hTT
  have e : ((gammaHot d h c ρ s : ℚ) : ℝ) = 1 - (1 - 1 / 400) / (ω : ℝ) := by
    rw [gammaHot, ← hωdef]; push_cast; ring
  rw [e]
  exact key

/-- TT_OUT per tile at a protocol and tiles meeting v2-hot's per-tile accounting gives `GγSampled` at
`gammaHot d h c ρ s`. -/
theorem pearlCSampledHotAt {Q R S : Type} [Fintype Q] [DecidableEq Q] [Fintype R] [Fintype S] (CM : CostModel Q R S)
    (P : Protocol Q R S) (TR : TileRules Q R S) (D : Layout → Prop) (d : PearlCDevice) (h : HotSizing) (c ρ : ℚ)
    (s : Shape) (hρ : ρ < 1) (hC : 0 < creditDevHot d s) (hW0 : 0 < wrefDevHot d h c s)
    (hacc : HotTileAccounting P TR D d h c ρ s) (hTT : TTOutTile CM P TR D (1 / 400) εPearlC) :
    GγSampled CM P TR D (gammaHot d h c ρ s : ℝ) εPearlC := by
  have hden : 0 < (1 - ρ) * creditDevHot d s := mul_pos (by linarith) hC
  set ω := wrefDevHot d h c s / ((1 - ρ) * creditDevHot d s) with hωdef
  have hω0 : 0 < ω := div_pos hW0 hden
  have hid : wrefDevHot d h c s = ω * ((1 - ρ) * creditDevHot d s) := by
    rw [hωdef, div_mul_cancel₀ _ hden.ne']
  have hW : ∀ U : Workload, U.InDomain P D → ∀ (H : Q → R) (s' : S), ∀ g < (TR.tiling U.layout).NT, ∀ act : Codes,
      TR.capOK H s' U g act → TR.Wcred U.layout g act ≤ (ω : ℝ) * TR.credit H s' U g act := by
    intro U hU H s' g hg act hcap
    obtain ⟨t, ht, hw, _, hcr⟩ := hacc U hU g hg act
    rw [hw, hid]
    have := hcr H s' hcap
    have e2 : ((ω * ((1 - ρ) * creditDevHot d s) * t : ℚ) : ℝ) =
        (ω : ℝ) * (((1 - ρ) * creditDevHot d s * t : ℚ) : ℝ) := by
      push_cast; ring
    rw [e2]
    exact mul_le_mul_of_nonneg_left this (by exact_mod_cast hω0.le)
  have hWc : ∀ U : Workload, U.InDomain P D → ∀ g < (TR.tiling U.layout).NT, ∀ act : Codes,
      TR.Wcred U.layout g act ≤ TR.Wref U.layout g := by
    intro U hU g hg act
    obtain ⟨t, _, _, hle, _⟩ := hacc U hU g hg act
    exact hle
  have key := gammaSampled CM P TR D (1 / 400) (ω : ℝ) εPearlC (by norm_num) (by exact_mod_cast hω0) hW hWc hTT
  have e : ((gammaHot d h c ρ s : ℚ) : ℝ) = 1 - (1 - 1 / 400) / (ω : ℝ) := by
    rw [gammaHot, ← hωdef]; push_cast; ring
  rw [e]
  exact key

/-- TT_OUT at a protocol meeting v2-hot's chain-only per-unit accounting gives `G_γ` at `gammaHotChainOnly d h c ρ s`. -/
theorem pearlCGammaHotChainOnlyAt {Q R S : Type} [Fintype Q] [DecidableEq Q] [Fintype R] [Fintype S]
    (CM : CostModel Q R S) (P : Protocol Q R S) (D : Layout → Prop) (d : PearlCDevice) (h : HotSizing) (c ρ : ℚ)
    (s : Shape) (hK : 0 < creditDevHotChainOnly d s - ρ * creditDevHot d s) (hW0 : 0 < wrefDevHot d h c s)
    (hacc : HotUnitAccountingChainOnly P D d h c ρ s) (hTT : TTOut CM P D (1 / 400) εPearlC) :
    Gγ CM P D (gammaHotChainOnly d h c ρ s : ℝ) εPearlC := by
  set ω := wrefDevHot d h c s / (creditDevHotChainOnly d s - ρ * creditDevHot d s) with hωdef
  have hω0 : 0 < ω := div_pos hW0 hK
  have hid : wrefDevHot d h c s = ω * (creditDevHotChainOnly d s - ρ * creditDevHot d s) := by
    rw [hωdef, div_mul_cancel₀ _ hK.ne']
  have hW : ∀ U : Workload, U.InDomain P D → ∀ (H : Q → R) (s' : S), ∀ u < U.layout.N, ∀ act : Codes,
      P.actOK (U.layout.shape u) act → P.capOK H s' U u act → P.Wref U.layout u ≤ (ω : ℝ) * P.credit H s' U u act := by
    intro U hU H s' u hu act ha hcap
    obtain ⟨hw, hcr⟩ := hacc U hU H s' u hu act ha hcap
    rw [hw, hid]
    push_cast
    exact mul_le_mul_of_nonneg_left (by exact_mod_cast hcr) (by exact_mod_cast hω0.le)
  have key := gammaFromTTOut CM P D (1 / 400) (ω : ℝ) εPearlC (by exact_mod_cast hω0) hW hTT
  have e : ((gammaHotChainOnly d h c ρ s : ℚ) : ℝ) = 1 - (1 - 1 / 400) / (ω : ℝ) := by
    rw [gammaHotChainOnly, ← hωdef]; push_cast; ring
  rw [e]
  exact key

/-- TT_OUT per tile at a protocol and tiles meeting v2-hot's chain-only per-tile accounting gives `GγSampled` at
`gammaHotChainOnly d h c ρ s`. -/
theorem pearlCSampledHotChainOnlyAt {Q R S : Type} [Fintype Q] [DecidableEq Q] [Fintype R] [Fintype S]
    (CM : CostModel Q R S) (P : Protocol Q R S) (TR : TileRules Q R S) (D : Layout → Prop) (d : PearlCDevice)
    (h : HotSizing) (c ρ : ℚ) (s : Shape) (hK : 0 < creditDevHotChainOnly d s - ρ * creditDevHot d s)
    (hW0 : 0 < wrefDevHot d h c s) (hacc : HotTileAccountingChainOnly P TR D d h c ρ s)
    (hTT : TTOutTile CM P TR D (1 / 400) εPearlC) :
    GγSampled CM P TR D (gammaHotChainOnly d h c ρ s : ℝ) εPearlC := by
  set ω := wrefDevHot d h c s / (creditDevHotChainOnly d s - ρ * creditDevHot d s) with hωdef
  have hω0 : 0 < ω := div_pos hW0 hK
  have hid : wrefDevHot d h c s = ω * (creditDevHotChainOnly d s - ρ * creditDevHot d s) := by
    rw [hωdef, div_mul_cancel₀ _ hK.ne']
  have hW : ∀ U : Workload, U.InDomain P D → ∀ (H : Q → R) (s' : S), ∀ g < (TR.tiling U.layout).NT, ∀ act : Codes,
      TR.capOK H s' U g act → TR.Wcred U.layout g act ≤ (ω : ℝ) * TR.credit H s' U g act := by
    intro U hU H s' g hg act hcap
    obtain ⟨t, ht, hw, _, hcr⟩ := hacc U hU g hg act
    rw [hw, hid]
    have := hcr H s' hcap
    have e2 : ((ω * (creditDevHotChainOnly d s - ρ * creditDevHot d s) * t : ℚ) : ℝ) =
        (ω : ℝ) * (((creditDevHotChainOnly d s - ρ * creditDevHot d s) * t : ℚ) : ℝ) := by
      push_cast; ring
    rw [e2]
    exact mul_le_mul_of_nonneg_left this (by exact_mod_cast hω0.le)
  have hWc : ∀ U : Workload, U.InDomain P D → ∀ g < (TR.tiling U.layout).NT, ∀ act : Codes,
      TR.Wcred U.layout g act ≤ TR.Wref U.layout g := by
    intro U hU g hg act
    obtain ⟨t, _, _, hle, _⟩ := hacc U hU g hg act
    exact hle
  have key := gammaSampled CM P TR D (1 / 400) (ω : ℝ) εPearlC (by norm_num) (by exact_mod_cast hω0) hW hWc hTT
  have e : ((gammaHotChainOnly d h c ρ s : ℚ) : ℝ) = 1 - (1 - 1 / 400) / (ω : ℝ) := by
    rw [gammaHotChainOnly, ← hωdef]; push_cast; ring
  rw [e]
  exact key

section Twins

variable {Q R S : Type} [Fintype Q] [DecidableEq Q] [Fintype R] [Fintype S] (CM : CostModel Q R S)
'''


def twin(rec, pr, cast, h, cterm, n, tile, co=False):
    CO = "ChainOnly" if co else ""
    name = f"pearlC{'Sampled' if tile else 'Gamma'}Sm120v2Hot{rec}{cast}{CO}_{n}"
    price = "1047/125 = 8.376" if rec else "8.00"
    what = "per audit tile, " if tile else ""
    reading = "chain-only, " if co else ""
    doc = (f"/-- **v2-hot at the cap 1/1,000, {reading}{what}{n}³**, FP32 at {price}, the honest cast at {float(h):g}, "
           f"under any H_i sizing rule `h`: γ = `gammaHot{CO} d h ({cterm}) (1 / 1000) sh{n}` (`gammaHot{CO}_…` give its "
           f"values). -/")
    lines, rest = [], doc
    while len(rest) > 120:
        cut = rest.rindex(" ", 0, 120)
        lines.append(rest[:cut])
        rest = rest[cut + 1:]
    doc = "\n".join(lines + [rest])
    pos = (f"(by rw [creditDevHotChainOnly, creditDevHot, creditDev, hG, hp]\n        norm_num [{pr}, Params.pi, sh{n}])"
           if co else f"(by rw [creditDevHot, creditDev, hG, hp]\n        norm_num [{pr}, Params.pi, sh{n}])")
    posw = (f"(by have h0 := h.cost_nonneg {pr} sh{n} (by norm_num [{pr}])\n"
            f"        rw [wrefDevHot, creditDevHot, creditDev, hG, hp]\n"
            f"        generalize h.cost {pr} sh{n} = x at h0 ⊢\n"
            f"        norm_num [{pr}, Params.pi, sh{n}]\n"
            f"        linarith)")
    if tile:
        return name, f'''
{doc}
theorem {name}
    (P : Protocol Q R S) (TR : TileRules Q R S) (D : Layout → Prop) (d : PearlCDevice) (h : HotSizing)
    (hG : d.G = 0) (hp : d.prices = {pr})
    (hacc : HotTileAccounting{CO} P TR D d h ({cterm}) (1 / 1000) sh{n})
    (hTT : TTOutTile CM P TR D (1 / 400) εPearlC) :
    GγSampled CM P TR D (gammaHot{CO} d h ({cterm}) (1 / 1000) sh{n} : ℝ) εPearlC :=
  pearlCSampledHot{CO}At CM P TR D d h _ _ _{"" if co else " (by norm_num)"}
    {pos}
    {posw}
    hacc hTT
'''
    return name, f'''
{doc}
theorem {name}
    (P : Protocol Q R S) (D : Layout → Prop) (d : PearlCDevice) (h : HotSizing) (hG : d.G = 0)
    (hp : d.prices = {pr})
    (hacc : HotUnitAccounting{CO} P D d h ({cterm}) (1 / 1000) sh{n})
    (hTT : TTOut CM P D (1 / 400) εPearlC) :
    Gγ CM P D (gammaHot{CO} d h ({cterm}) (1 / 1000) sh{n} : ℝ) εPearlC :=
  pearlCGammaHot{CO}At CM P D d h _ _ _{"" if co else " (by norm_num)"}
    {pos}
    {posw}
    hacc hTT
'''


def value(rec, pr, p, cast, h, c, cterm, n, rule, co=False):
    CO = "ChainOnly" if co else ""
    g = gamma(p, rule, c, n, co)
    name = f"gammaHot{CO}_sm120v2Hot{rec}{cast}_{rule}_{n}"
    price = "1047/125 = 8.376" if rec else "8.00"
    reading = ", chain-only" if co else ""
    unf = ("gammaHotChainOnly, wrefDevHot, creditDevHotChainOnly, creditDevHot, creditDev" if co
           else "gammaHot, wrefDevHot, creditDevHot, creditDev")
    return name, g, f'''
/-- v2-hot's γ at the cap 1/1,000{reading}, {n}³, FP32 at {price}, the honest cast at {float(h):g}, sizing
`{rule}`{" (any constant c₀)" if rule == "publicConst" else " (its FMA at 8.46)"}:
`{lean(g).replace(' ', '')}` ({pct(g)}). -/
theorem {name}
    {"(c₀ : ℚ) " if rule == "publicConst" else ""}(d : PearlCDevice) (hG : d.G = 0) (hp : d.prices = {pr}) :
    gammaHot{CO} d {LEAN_RULE[rule]} ({cterm}) (1 / 1000) sh{n} =
      {lean(g)} := by
  rw [{unf}, hG, hp]
  norm_num [HotSizing.{rule}, {pr}, Params.pi, sh{n}]
'''


def value_c0(rec, pr, p, cast, h, c, cterm, n, co=False):
    """`HotSizing.publicConst C0`'s value: the any-`c₀` lemma at `C0` where the cast has one, else by `norm_num`."""
    CO = "ChainOnly" if co else ""
    g = gamma(p, "publicConst", c, n, co)
    generic = f"gammaHot{CO}_sm120v2Hot{rec}{cast}_publicConst_{n}"
    name = f"gammaHot{CO}_sm120v2Hot{rec}{cast}_publicConst{C0}_{n}"
    price = "1047/125 = 8.376" if rec else "8.00"
    reading = ", chain-only" if co else ""
    unf = ("gammaHotChainOnly, wrefDevHot, creditDevHotChainOnly, creditDevHot, creditDev" if co
           else "gammaHot, wrefDevHot, creditDevHot, creditDev")
    proof = (f" :=\n  {generic} {C0} d hG hp\n" if cast in ALL_RULES else
             f" := by\n  rw [{unf}, hG, hp]\n  norm_num [HotSizing.publicConst, {pr}, Params.pi, sh{n}]\n")
    return name, g, f'''
/-- v2-hot's γ at the cap 1/1,000{reading}, {n}³, FP32 at {price}, the honest cast at {float(h):g}, at the fixed sizing
rule `HotSizing.publicConst {C0}` (`ttout-restatements.md` §8): `{lean(g).replace(' ', '')}` ({pct(g)}). -/
theorem {name}
    (d : PearlCDevice) (hG : d.G = 0) (hp : d.prices = {pr}) :
    gammaHot{CO} d (HotSizing.publicConst {C0}) ({cterm}) (1 / 1000) sh{n} =
      {lean(g)}{proof}'''


def rewrap_docs(text):
    """Refill each `/-- … -/` docstring longer than 120 columns."""
    import re

    def fill(m):
        block = m.group(0)
        if all(len(line) <= 120 for line in block.splitlines()):
            return block
        words, lines, line = block[4:-3].split(), [], "/--"
        for w in words:
            if len(line) + 1 + len(w) > 120:
                lines.append(line)
                line = w
            else:
                line += " " + w
        lines.append(line + " -/" if len(line) + 3 <= 120 else line + "\n-/")
        return "\n".join(lines)
    return re.sub(r"/-- .*? -/", fill, text, flags=re.S)


def main():
    out, vals, table = [HEADER], ["\nend Twins\n\n/-! ## The values, per sizing rule -/\n"], []
    for rec, (pr, p, cof) in RECORDS.items():
        for cast, h in CASTS.items():
            c, cterm = cof(h)
            for co in (False, True):
                for n in SIZES:
                    for tile in (False, True):
                        out.append(twin(rec, pr, cast, h, cterm, n, tile, co)[1])
                    for rule in RULES if cast in ALL_RULES else ():
                        name, g, text = value(rec, pr, p, cast, h, c, cterm, n, rule, co)
                        vals.append(text)
                        table.append((name, lean(g), pct(g)))
                    name, g, text = value_c0(rec, pr, p, cast, h, c, cterm, n, co)
                    vals.append(text)
                    table.append((name, lean(g), pct(g)))
    here = Path(__file__).resolve().parent
    text = "".join(out + vals) + "\nend Pouw.PearlC\n"
    (here / "Pouw/PearlC/HotGamma.lean").write_text(rewrap_docs(text))
    for row in table:
        print(*row, sep="\t")


if __name__ == "__main__":
    main()
